Added types retrieving for BiqQuery
ksyusha123/logica pull request #38
Opened 2023-12-10 18:04 UTC by Themplarer

2023-12-11 16:52 UTC, ksyusha123 requested changes

2023-12-11 16:52 UTC, ksyusha123 commented on type_inference/bigquery_type_retriever.py
> +    assert False, 'Unknown BigQuery type! %s' % type
Давай более осмысленное исключение кидать)

2023-12-11 16:52 UTC, ksyusha123 commented on type_inference/type_retrieval_service.py
> +    columns = {table: json.loads(type) for table, type in query.to_dataframe().set_index('table_name').to_dict()['columns'].items()}
Ух, тяжело читать такую длинную строчку

2023-12-11 16:52 UTC, ksyusha123 commented on type_inference/bigquery_type_retriever.py
> +      fields = (f'{field_name}: {self.UnpackTypeWithCaching(field_type)}' for field_name, field_type in fields.items())
Переприсваивание переменной меняет ее смысл, давай разные имена дадим

2023-12-11 16:52 UTC, ksyusha123 commented on type_inference/type_retrieval_service.py
> +      fields = (f'{column}: {self.type_retriever.UnpackTypeWithCaching(udt_type)}' for column, udt_type in sorted(table_columns.items()))
Если мы следуем pep8, то там длина строки 79 символов. Давай пройдемся по измененным файлам и укоротим строки. Где-то придется отказаться от синтаксиса for в одну строчку

2023-12-25 09:25 UTC, Themplarer commented on type_inference/bigquery_type_retriever.py
> +    assert False, 'Unknown BigQuery type! %s' % type
Ну, это крайне маловероятный случай, который обычно таким ассертом в логике закрыт. Сделал исключение

2023-12-25 09:25 UTC, Themplarer commented on type_inference/type_retrieval_service.py
> +    columns = {table: json.loads(type) for table, type in query.to_dataframe().set_index('table_name').to_dict()['columns'].items()}
Переделал

2023-12-25 09:27 UTC, Themplarer commented on type_inference/type_retrieval_service.py
> +      fields = (f'{column}: {self.type_retriever.UnpackTypeWithCaching(udt_type)}' for column, udt_type in sorted(table_columns.items()))
Не уверен, что следуем) Как минимум названия функций, вроде, не соответствуют. Добавил переносов местами

2023-12-25 09:28 UTC, Themplarer commented on type_inference/bigquery_type_retriever.py
> +      fields = (f'{field_name}: {self.UnpackTypeWithCaching(field_type)}' for field_name, field_type in fields.items())
Рассчёт был на то, что это всё равно "временный вид" данных, поэтому можно и переприсвоить. Разделил имена

2023-12-30 16:23 UTC, ksyusha123 approved these changes

2023-12-30 16:28 UTC, merged