Added TypesGraph
ksyusha123/logica pull request #4
Opened 2023-03-16 05:03 UTC by Themplarer

2023-03-18 11:25 UTC, ksyusha123 requested changes

2023-03-18 11:25 UTC, ksyusha123 commented on type_inference/ast_traverse.py
> +  for conjunct in rule["body"]["conjunction"]["conjunct"]:
Предикаты могут быть не только в теле, но и в хеде. Пример: Q(x: T(y));

2023-03-18 11:25 UTC, ksyusha123 commented on type_inference/types.py
> +  def connect(self, first_variable: str, second_variable: str, context):
Чего-то я не очень поняла идею с первой и второй переменной. Как это будет выглядеть, например, для предиката Q(x:, y:) :- T(x:), y == 5?

2023-03-18 11:25 UTC, ksyusha123 commented on type_inference/types.py
> +    self.variable_types = dict()
А это зачем?

2023-03-18 11:25 UTC, ksyusha123 commented on type_inference/ast_traverse.py
> +    # todo: use this result - separate task
Кажется, нужно эту логику тоже продумать. Вроде Артем на каком-то из созвонов говорил как раз про графы. Мб можно вместе с ним сесть и подумать (заодно ему сразу задачу подкинуть) :)

2023-03-18 17:05 UTC, Themplarer commented on type_inference/types.py
> +    self.variable_types = dict()
Может пригодиться на следующих этапах для соответствия названия переменной и её типа

2023-03-18 17:08 UTC, Themplarer commented on type_inference/ast_traverse.py
> +    # todo: use this result - separate task
Конечно, но я глянул на список задач, а там на это выделены отдельные задачи. В частности, на этом месте после построения графа может идти эта
![image](https://user-images.githubusercontent.com/12811221/226122039-6141344f-49b2-454e-9ee0-3e5d2486a32b.png)

2023-03-18 17:16 UTC, Themplarer commented on type_inference/types.py
> +  def connect(self, first_variable: str, second_variable: str, context):
Была идея сделать граф, который для пары вершин-переменных содержал бы некие "контексты" (то есть где они вместе используются, на каких местах и прочее). На унификации и какие-нибудь другие конструкции с 2 аргументами это нормально ложится, на конструкции с 1 переменной - есть идеи, но более костыльные.

Видимо, лучше передизайнить, нужно подумать как положить это на граф

2023-03-27 05:09 UTC, ksyusha123 approved these changes

2023-03-27 05:09 UTC, merged