predicate and predicate arg info model
ksyusha123/logica pull request #5
Opened 2023-03-22 17:22 UTC by C-reshetka

2023-03-23 09:57 UTC, ksyusha123 requested changes

2023-03-23 09:57 UTC, ksyusha123 commented on type_inference/predicate_argument_info.py
> +  def __init__(self, name: str, type: type):
У нас типы будут не такими же, как в питоне, кажется, а какие-то свои кастомные (мы это на прошлом созвоне обсуждали, что-то вроде TypeInfo)

2023-03-23 09:57 UTC, ksyusha123 commented on type_inference/predicate_argument_info.py
> +    return self.name
Думаю, что тип тоже хорошо бы выводить. Например, вот так: {self.name} : {self.type}

2023-03-23 09:57 UTC, ksyusha123 commented on type_inference/predicate_info.py
> +    result = sub(r"([_\-])+", " ", string).title().replace(" ", "")
Мне кажется, не стоит убирать нижние подчеркивания и дефисы, это только путает

2023-03-23 09:57 UTC, ksyusha123 commented on type_inference/predicate_info.py
> +    self.name = self.__format_name(name)
Почему метод с одним подчеркиванием, а его вызов  - с двумя?

2023-03-23 09:57 UTC, ksyusha123 commented on type_inference/predicate_argument_info.py
> +
Это про задачу больше комментарий: прикольно, что красиво описал предикат, но задача была не только в этом. Нужно было еще для встроенных предикатов эти типы сразу и вывести. Как в табличке с задачей и написано для примера: если есть предикат <, то мы делаем вывод, что его аргументами должны быть либо числа либо строки, для синуса - только числа и тд. Может быть сделать метод try_create(), который будет делать все возможные проверки. То есть что-то в духе: если имя предиката синус, то аргумент должен быть числом, если нам передали не число, то вернуть false (типа не смогли создать предикат)

2023-03-25 10:50 UTC, Themplarer commented on type_inference/predicate_info.py
> +    result = sub(r"([_\-])+", " ", string).title().replace(" ", "")
Возможно, стоит ещё компилировать регулярку и хранить в поле

2023-10-25 16:07 UTC, closed without merging